### PR TITLE
Retinting after source update

### PR DESCRIPTION
**Pull request by YNesenberend**
I tried to use this package, because it was really easy to implement and use - well done. Only problem is the same issue some people are also having, with the retint not being applied after source change. I added what I did in my code to fix this issue. :)

### CODE REVIEW

**Comment by woutermeuwis** [comment]
I have implemented the same changes locally and can confirm this fixes issue #9

**Comment by YNesenberend** [comment]
@shrutinambiar mind accepting this request? :)

**Comment by shrutinambiar** [comment]
@YNesenberend Really sorry for the delay. Unfortunately, I don't have much time currently to maintain this repo (exams)

**Comment by YNesenberend** [comment]
@shrutinambiar no problem :) Hope it goes well with your exams!

**Pull request merged**
